# Manually maintained – not generated by generate_tools.py.
# Add this command here because CreateLinearDimension is not yet published in the
# multiconn-archicad library.  When the library ships the corresponding Pydantic
# models (CreateLinearDimensionParameters / CreateLinearDimensionResult), migrate
# this file to the generated tapir/element_commands.py instead.

import logging
from typing import Optional

from pydantic import BaseModel, Field, ValidationError
from multiconn_archicad.basic_types import Port
from tapir_archicad_mcp.context import multi_conn_instance
from tapir_archicad_mcp.tools.tool_registry import register_tool_for_dispatch

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Parameter / result models
# ---------------------------------------------------------------------------

class DimensionPoint(BaseModel):
    """A single point in a linear dimension chain."""
    x: float = Field(..., description="X coordinate in meters.")
    y: float = Field(..., description="Y coordinate in meters.")
    elementGuid: Optional[str] = Field(
        default=None,
        description="GUID of the element to associate (optional). Enables associative dimensioning."
    )
    neigIndex: Optional[int] = Field(
        default=None,
        description=(
            "Geometry point index on the element (optional). "
            "Wall: 1=refStart, 2=refEnd, 11=oppStart, 21=oppEnd. "
            "Slab: vertex 1-N. Column: 1. Beam: 1=start, 2=end."
        )
    )


class CreateLinearDimensionParameters(BaseModel):
    """Parameters for the TapirCommand.CreateLinearDimension command (v1.3.3)."""
    dimensionPoints: list[DimensionPoint] = Field(
        ...,
        min_length=2,
        description=(
            "Ordered list of points to dimension. Each point requires x/y coordinates. "
            "Optionally include elementGuid + neigIndex for associative dimensioning."
        )
    )
    refLineOffset: float = Field(
        ...,
        description=(
            "Perpendicular offset of the dimension line in meters. "
            "Positive or negative controls which side. Typical value: 0.5 or -0.5."
        )
    )
    isHorizontal: Optional[bool] = Field(
        default=None,
        description=(
            "true = horizontal chain (measures X distances). "
            "false = vertical chain (measures Y distances). "
            "Auto-detected from points if omitted."
        )
    )
    linPen: Optional[int] = Field(
        default=None,
        description="Pen index for dimension lines (1-255). Default: 1."
    )
    textPen: Optional[int] = Field(
        default=None,
        description="Pen index for dimension text (1-255). Default: 1."
    )
    storyIndex: Optional[int] = Field(
        default=None,
        description="Story index for placement. Default: 0 = active story."
    )


class CreateLinearDimensionResult(BaseModel):
    """Result returned by the TapirCommand.CreateLinearDimension command."""
    dimensionGuid: Optional[str] = Field(
        default=None,
        description="GUID of the created dimension element."
    )
    success: Optional[bool] = None
    error: Optional[str] = Field(
        default=None,
        description="Error message if success is false."
    )


# ---------------------------------------------------------------------------
# Tool function
# ---------------------------------------------------------------------------

def create_linear_dimension(
    port: int,
    params: CreateLinearDimensionParameters,
) -> CreateLinearDimensionResult:
    """
    Creates a linear dimension element on the floor plan.

    Use this to add linear / chain dimensions (cotas lineares) to walls,
    slabs, columns, beams, or arbitrary coordinate points.  The dimension
    line is placed perpendicular to the chain direction at the given
    refLineOffset distance.

    Semantic aliases: create dimension, add dimensions, annotate walls,
    dimensionar, cota linear, cotar elementos, dimensionar paredes,
    adicionar cotas.
    """
    multi_conn = multi_conn_instance.get()
    target_port = Port(port)
    if target_port not in multi_conn.active:
        raise ValueError(f"Port {port} is not an active Archicad connection.")
    conn_header = multi_conn.active[target_port]
    try:
        result_dict = conn_header.core.post_tapir_command(
            command="CreateLinearDimension",
            parameters=params.model_dump(mode="json", exclude_none=True),
        )
        return CreateLinearDimensionResult.model_validate(result_dict)

    except ValidationError as e:
        log.error(f"Validation error for CreateLinearDimension result: {e}")
        raise ValueError(f"Received an invalid response from the Archicad API: {e}")
    except Exception as e:
        log.error(f"Error executing CreateLinearDimension on port {port}: {e}")
        raise e


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------

register_tool_for_dispatch(
    create_linear_dimension,
    name="elements_create_linear_dimension",
    title="CreateLinearDimension",
    description=(
        "Creates a linear dimension element on the floor plan. "
        "Use to add dimensions / annotations to walls, slabs, columns, beams, or arbitrary points. "
        "Supports associative dimensioning (linked to element geometry). "
        "Aliases: create dimension, add dimensions, annotate walls, dimensionar, "
        "cota linear, cotar elementos, dimensionar paredes, adicionar cotas."
    ),
    params_model=CreateLinearDimensionParameters,
    result_model=CreateLinearDimensionResult,
)
